# Generated by Django 5.0.4 on 2024-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='imei',
            field=models.CharField(max_length=16),
        ),
    ]
