# Generated by Django 5.0.4 on 2024-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_asset_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='imsi',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
